<?php

namespace App\Modules\Admin\Users\Requests;

use App\Services\Request\ApiRequest;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class UserRequest extends ApiRequest{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(){

        return Auth::user()->userPermissionSet(['Root_Admin', 'USER_ACCESS']);
    }

    protected function getValidatorInstance()
    {
        $validator =  parent::getValidatorInstance(); // TODO: Change the autogenerated stub

        $validator->sometimes('password',['required', 'confirmed'],function($input){

            if(!empty($input->password) || (empty($input->password) && ($this->route()->getName() != "api.users.update"))) {
                        return true;
            }
            return false;
        });

        return $validator;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(){
        return [
            'firstname' => 'required',
            'lastname' => 'required',
            'email' => 'required',
            'phone' => 'required',
            'password' => 'required',
            'role_id' => 'required',
        ];
    }
}
